### ISSUE TITLE
na check error doesn't show which data frame has NA's (in ipython notebook)

### ISSUE THREAD

**Issue by buckleytom** [synthicity/urbansim_defaults#11]
this check here could maybe work better: https://github.com/synthicity/urbansim_defaults/blob/ec68a0b2fff79c66f00bc63c8232e55c580cce41/urbansim_defaults/utils.py#L78-L81

at line 78, it seems like it would print out which data frame has NA's. but i don't think it actually does. (see the output below). i ran into this while having a config file with NA's as parameters (as output by Estimation.ipynb)

it looks like this (at least in a notebook, not sure about python):

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-4-a65c0cc56983> in <module>()
     27     #"pusher",                    # push results to the web client
     28     #"clear_cache"                # clear the cache each year
---> 29 ], years=range(in_year, out_year))
     30 print "Finished", time.ctime()
 
d:\urbansim_windows\urbansim\urbansim\sim\simulation.pyc in run(models, years, data_out, out_interval)
   1524                 model = get_model(model_name)
   1525                 t2 = time.time()
-> 1526                 model()
   1527                 print("Time to execute model '{}': {:.2f}s".format(
   1528                       model_name, time.time()-t2))
 
d:\urbansim_windows\urbansim\urbansim\sim\simulation.pyc in __call__(self)
    679             kwargs = _collect_variables(names=self._argspec.args,
    680                                         expressions=self._argspec.defaults)
--> 681             return self._func(**kwargs)
    682
    683     def _tables_used(self):
 
d:\urbansim_windows\urbansim_defaults\urbansim_defaults\models.pyc in hlcm_simulate(households, buildings, aggregations, settings)
     46                               "building_id","residential_units",
     47                               "vacant_residential_units",
---> 48                               settings.get("enable_supply_correction", None))
     49 
     50 
 
d:\urbansim_windows\urbansim_defaults\urbansim_defaults\utils.pyc in lcm_simulate(cfg, choosers, buildings, join_tbls, out_fname, supply_fname, vacant_fname, enable_supply_correction)
    337         additional_columns +=[enable_supply_correction["price_col"]]
    338     locations_df = to_frame(buildings, join_tbls, cfg,
--> 339                             additional_columns=additional_columns)
    340 
    341     available_units = buildings[supply_fname]
 
d:\urbansim_windows\urbansim_defaults\urbansim_defaults\utils.pyc in to_frame(tbl, join_tbls, cfg, additional_columns)
    193     else:
    194         df = tables[0].to_frame(columns)
--> 195     check_nas(df)
    196     return df
    197 
 
d:\urbansim_windows\urbansim_defaults\urbansim_defaults\utils.pyc in check_nas(df)
     79                   (df_cnt-s_cnt, df_cnt, col)
     80
---> 81     assertnot fail, "NAs were found in dataframe, please fix"
     82
     83

**Comment by buckleytom** [comment]
it could also be that we need to log these errors in a better way.

**Comment by fscottfoti** [comment]
It kind of does show which column is the problem, in the sense that the previous line is

Found 46350 nas or inf (out of 1841284) in column general_type

So it doesn't in the exception, but it does in the output.

**Comment by buckleytom** [comment]
ah, sorry i didn't see that in the log. i guess i was not looking in the right place. i'll close this then.

**Comment by fscottfoti** [comment]
It looks like your error happened in the supply and demand part of things so it's possible it's different for some reason - I would check and make sure it's there...

**Comment by buckleytom** [comment]
will do
